[env]
SRC_LIB_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "so", mapping = { macos = "dylib", windows = "dll" } }
DST_LIB_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "so", mapping = { windows = "pyd" } }
SRC_LIB_NAME = "lib${CARGO_MAKE_CRATE_FS_NAME}.${SRC_LIB_EXT}"
DST_LIB_NAME = "${CARGO_MAKE_CRATE_FS_NAME}.${DST_LIB_EXT}"
SRC_LIB_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release"
DST_LIB_DIR = "../../pyxel/lib"

[tasks.clean]
clear = true
dependencies = ["cargo-clean"]
script = '''
rm -rf ${DST_LIB_DIR}
'''

[tasks.extension-build]
script = '''
echo mv ${SRC_LIB_DIR}/${SRC_LIB_NAME} ${SRC_LIB_DIR}/${DST_LIB_NAME}
'''

[tasks.build]
dependencies = ["cargo-build", "extension-build"]

[tasks.build-release]
clear = true
dependencies = ["cargo-build-release"]
script = '''
mv ${SRC_LIB_DIR}/${SRC_LIB_NAME} ${SRC_LIB_DIR}/${DST_LIB_NAME}"
cp -f ${SRC_LIB_DIR}/${SRC_LIB_NAME} ${DST_LIB_DIR}/${DST_LIB_NAME}"
'''

[tasks.test]
clear = true
script = '''
'''
