extend = "../Makefile.toml"

[env]
PLATFORM_NAME = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "linux", mapping = { macos = "mac", windows = "windows" } }
PYTHON_LIB_DIR = "../../pyxel/lib/${PLATFORM_NAME}"
DEBUG_TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug"
RELEASE_TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release"

SRC_LIB_DIR = { source = "${CARGO_MAKE_TASK}", default_value = "${DEBUG_TARGET_DIR}", mapping = { build-release = "${RELEASE_TARGET_DIR}" } }
SRC_LIB_EXT = { source = "${PLATFORM_NAME}", default_value = "so", mapping = { mac = "dylib", windows = "dll" } }
SRC_LIB_NAME = "lib${CARGO_MAKE_CRATE_FS_NAME}.${SRC_LIB_EXT}"
SRC_LIB_PATH = "${SRC_LIB_DIR}/${SRC_LIB_NAME}"

DST_LIB_DIR = { source = "${CARGO_MAKE_TASK}", default_value = "${DEBUG_TARGET_DIR}", mapping = { build-release = "${PYTHON_LIB_DIR}" } }
DST_LIB_EXT = { source = "${PLATFORM_NAME}", default_value = "so", mapping = { windows = "pyd" } }
DST_LIB_NAME = "${CARGO_MAKE_CRATE_FS_NAME}.${DST_LIB_EXT}"
DST_LIB_PATH = "${DST_LIB_DIR}/${DST_LIB_NAME}"

[tasks.copy-lib]
private = true
script = '''
echo copy ${SRC_LIB_PATH} to ${DST_LIB_PATH}
cp ${SRC_LIB_PATH} ${DST_LIB_PATH}
'''

[tasks.format]
alias = "cargo-format"

[tasks.clean]
dependencies = ["cargo-clean"]
script = '''
rm -rf ${PYTHON_LIB_DIR}
'''

[tasks.build]
dependencies = ["cargo-build", "copy-lib"]

[tasks.build-release]
dependencies = ["cargo-build-release", "copy-lib"]

[tasks.test]
dependencies = ["build"]
script = '''
python3 tests/*.py
'''
