[package]
name = "pyxelengine"
version = "0.1.0"
authors = ["Takashi Kitao <takashi.kitao@gmail.com>"]
edition = "2018"

[lib]
name = "pyxel"

[dependencies]
once_cell = "1.5.2"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image"]