[config]
skip_core_tasks = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.cargo-clean]
script = '''
cargo clean
'''

[tasks.cargo-build]
script = '''
cargo build
'''

[tasks.cargo-build-release]
script = '''
cargo build --release
'''

[tasks.cargo-test]
script = '''
cargo test
'''

[tasks.clean]
alias = "cargo-clean"

[tasks.build]
alias = "cargo-build"

[tasks.build-release]
alias = "cargo-build-release"

[tasks.test]
alias = "cargo-test"
