[config]
skip_core_tasks = true

[tasks.cargo-format]
install_crate = "rustfmt"
script = '''
cargo fmt -- --emit=files
'''

[tasks.cargo-clean]
script = '''
cargo clean
'''

[tasks.cargo-build]
script = '''
cargo build
'''

[tasks.cargo-build-release]
script = '''
cargo build --release
'''

[tasks.cargo-test]
script = '''
cargo test
'''
